title: 'Nicolas Bages'
author:
  name: 'Nicolas Bages'
  email: nicolas.bages@spyesx.fr
taxonomies:
  - category
  - tag
metadata:
  description: 'homo-numerictus since 1986'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
footer_note: 'Made with <span class="module__footer__love">♡</span> and some <a href="https://github.com/spyesx/spyesx.fr">tools</a>.'